package View;

import Cefet.Persistence.PersistenceSingleton;
import Exercicio2b.controller.CadastroJpaController;
import Exercicio2b.model.Cadastro;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alunos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        dataNasc = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputData = new javax.swing.JTextField();
        inputTel = new javax.swing.JTextField();
        inputEnd = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoBuscar = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome.setText("Nome:");

        dataNasc.setText("Data de Nasc: ");

        telefone.setText("Telefone:");

        endereco.setText("Endereço:");

        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "data nasc", "telefone", "endereço", "id"
            }
        ));
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRemover)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefone)
                                    .addComponent(endereco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputEnd)
                                    .addComponent(inputTel))))
                        .addGap(184, 548, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNasc)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone)
                    .addComponent(inputTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco)
                    .addComponent(inputEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemover)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoAdicionar)
                    .addComponent(botaoBuscar))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();
        CadastroJpaController cadController = new CadastroJpaController(ponte);

        DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();

        List<Cadastro> listaCadastro = cadController.findCadastroEntities();
        int tamanho = listaCadastro.size();

        for (int i = 0; i < tamanho; i++) {
            Cadastro cad = listaCadastro.get(i);
            String id = String.valueOf(cad.getId());
            String vetor[] = new String[]{cad.getNome(), cad.getDataNasc(), cad.getTelefone(), cad.getEndereco(), id};
            dtm.addRow(vetor);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();
        CadastroJpaController cadController = new CadastroJpaController(ponte);

        Cadastro c1 = new Cadastro();

        DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();

        String nome = inputNome.getText();
        String data = inputData.getText();
        String tel = inputTel.getText();
        String end = inputEnd.getText();

        c1.setNome(nome);
        c1.setDataNasc(data);
        c1.setTelefone(tel);
        c1.setEndereco(end);

        cadController.create(c1);

        if ((!nome.equals("")) && (!data.equals("")) && (!tel.equals("")) && (!end.equals(""))) {
            cadController.create(c1);
            System.out.println(c1.toString());
            String valores[] = new String[]{nome, data, tel, end, String.valueOf(c1.getId())};
            dtm.addRow(valores);
        } else {
            JOptionPane.showMessageDialog(this, "Há campo(s) em branco!");
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();
        CadastroJpaController cadController = new CadastroJpaController(ponte);

        Cadastro c1 = new Cadastro();

        DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();
        tableUsuarios.getModel();
        int rowSelected = tableUsuarios.getSelectedRow();

        String nome = inputNome.getText();
        String data = inputData.getText();
        String tel = inputTel.getText();
        String end = inputEnd.getText();

        if (rowSelected == -1) {

            c1.setDataNasc(data);
            c1.setNome(nome);
            c1.setTelefone(tel);
            c1.setEndereco(end);
            cadController.create(c1);
            String converte = String.valueOf(c1.getId());
            String valores[] = new String[]{nome, data, tel, end, converte};
            dtm.addRow(valores);
        } else {
            try {
                String converte = String.valueOf(c1.getId());
                dtm.setValueAt(nome, rowSelected, 0);
                dtm.setValueAt(data, rowSelected, 1);
                dtm.setValueAt(tel, rowSelected, 2);
                dtm.setValueAt(end, rowSelected, 3);
                dtm.setValueAt(converte, rowSelected, 4);
              
                c1.setNome(nome);
                c1.setDataNasc(data);
                c1.setTelefone(tel);
                c1.setEndereco(end);
               // c1.setId(Long.parseLong(converte));
                cadController.edit(c1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro!");
            }
        }


    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();
        CadastroJpaController cadController = new CadastroJpaController(ponte);

        Cadastro c1 = new Cadastro();
        DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();
        int rowSelected = tableUsuarios.getSelectedRow();

        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Não há linha selecionada");
        } else {
            int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja remover esta linha?", "Confirmação de opção", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                try{
                    dtm.removeRow(rowSelected);
                   Long id = (c1.getId());
                    cadController.destroy(id);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro! O id não foi encontrado.");
                }
            }
        }


    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        int row = tableUsuarios.rowAtPoint(evt.getPoint());

        DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();

        inputNome.setText(dtm.getValueAt(row, 0).toString());
        inputData.setText(dtm.getValueAt(row, 1).toString());
        inputTel.setText(dtm.getValueAt(row, 2).toString());
        inputEnd.setText(dtm.getValueAt(row, 3).toString());

    }//GEN-LAST:event_tableUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel dataNasc;
    private javax.swing.JLabel endereco;
    private javax.swing.JTextField inputData;
    private javax.swing.JTextField inputEnd;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputTel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
